# Generated by Django 5.2.5 on 2025-09-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse utilisateur')),
                ('poste', models.TextField(blank=True, null=True, verbose_name='Poste')),
                ('tel1', models.TextField(blank=True, null=True, verbose_name='Telephone 1')),
                ('tel2', models.TextField(blank=True, null=True, verbose_name='Telephone 2')),
                ('nationnalite', models.TextField(blank=True, null=True, verbose_name='Nationnalité')),
                ('photo', models.FileField(blank=True, null=True, upload_to='account/photos/', verbose_name='photo')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greffe_juridiction', to='start.juridictions')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Image de la Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('chef_greffe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='greffe.account', verbose_name='Chef de Greffe')),
            ],
        ),
    ]
