# Generated by Django 5.2.5 on 2025-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greffe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='Prenom'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='Nom utilisateur'),
        ),
    ]
