# Generated by Django 5.2.5 on 2025-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type_document', models.TextField(choices=[('contrat_travail', 'Contrat de travail'), ('convention_stage', 'Convention de stage'), ('lettre_embauche', "Lettre d'embauche"), ('lettre_convocation', 'Lettre de convocation'), ('lettre_licenciement', 'Lettre de licenciement'), ('reglement_interieur', 'Modèle règlement intérieur')], default='lettre')),
                ('categorie', models.TextField(choices=[('employeur', 'Employeur'), ('employe', 'Employé')], default='employeur')),
                ('contenu', models.TextField(help_text='Utilisez {{ nom }}, {{ date }} pour les champs dynamiques')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
