# Generated by Django 5.2.5 on 2025-09-29 08:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionrequest',
            name='piece_identite',
            field=models.FileField(upload_to=users.models.contribution_upload_to, verbose_name="Pièce d'identité (PDF ou image)"),
        ),
    ]
