# Generated by Django 5.0.3 on 2025-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenu', models.TextField(help_text='Utilisez {{ nom }}, {{ date }} pour les champs dynamiques')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
