# Generated by Django 5.2.5 on 2025-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugement',
            fields=[
                ('idJugement', models.AutoField(primary_key=True, serialize=False)),
                ('numJugement', models.CharField(max_length=100, null=True)),
                ('numRg', models.CharField(blank=True, max_length=100, null=True)),
                ('dateJugement', models.DateField()),
                ('president', models.CharField(max_length=100)),
                ('jugeConsulaire1', models.CharField(max_length=255, null=True)),
                ('jugeConsulaire2', models.CharField(max_length=255, null=True)),
                ('greffier', models.CharField(max_length=100)),
                ('demanderesses', models.CharField(max_length=255)),
                ('defenderesses', models.CharField(max_length=255)),
                ('avocatsDemanderesses', models.TextField()),
                ('avocatsDefenderesses', models.TextField()),
                ('objet', models.TextField()),
                ('decision', models.FileField(upload_to='decisions/')),
                ('jugement_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
