# Generated by Django 5.2.5 on 2025-09-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisprudence', '0001_initial'),
        ('start', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugement',
            name='idAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugement',
            name='juridiction',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction'),
        ),
    ]
