# Generated by Django 5.2.5 on 2025-09-20 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du post (max 200 caractères).', max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant unique utilisé dans l’URL.', max_length=220, null=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='Contenu principal de l’article.', verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text='Image illustrant l’article (optionnel).', null=True, upload_to='blog_images/', verbose_name='Image')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', help_text='Définir si l’article est brouillon, publié ou archivé.', max_length=20, verbose_name='Statut')),
                ('type', models.CharField(choices=[('news', 'News'), ('contribution', 'Contribution')], default='news', help_text='Définir si l’article est une actualité ou contribution.', max_length=20, verbose_name='Type')),
                ('views', models.PositiveIntegerField(default=0, help_text='Nombre de fois que l’article a été consulté.', verbose_name='Vues')),
                ('shares', models.PositiveIntegerField(default=0, help_text='Nombre de fois que l’article a été partagé.', verbose_name='Partages')),
                ('is_published', models.BooleanField(default=False, help_text='Indique si l’article est diffusé ou non.', verbose_name='Diffusé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
