# Generated by Django 5.2.5 on 2025-10-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'En attente'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', help_text='Définir si l’article est brouillon, publié ou archivé.', max_length=20, verbose_name='Statut'),
        ),
    ]
