# Generated by Django 5.2.5 on 2025-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Explication fournie en cas de refus de l’article.', null=True, verbose_name='Motif de refus'),
        ),
    ]
