# Generated by Django 5.0.3 on 2025-07-05 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffaireRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAffaire', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numOrdre', models.IntegerField(verbose_name="Numéro d'ordre")),
                ('numRg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rg')),
                ('numRp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rp')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('mandatDepot', models.TextField(blank=True, null=True, verbose_name='Mandats de Dépôt')),
                ('detention', models.TextField(blank=True, null=True, verbose_name='Detention')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Prevention')),
                ('natureInfraction', models.TextField(blank=True, null=True, verbose_name='Nature des infractions')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('prevenus', models.TextField(blank=True, null=True, verbose_name='Prévenus')),
                ('demandeurs', models.TextField(blank=True, null=True, verbose_name='Demandeurs')),
                ('defendeurs', models.TextField(blank=True, null=True, verbose_name='Défendeurs')),
                ('appelants', models.TextField(blank=True, null=True, verbose_name='Appelants')),
                ('intimes', models.TextField(blank=True, null=True, verbose_name='Intimés')),
                ('partieCiviles', models.TextField(blank=True, null=True, verbose_name='Parties civiles')),
                ('civileResponsables', models.TextField(blank=True, null=True, verbose_name='Civiles Responsables')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
            ],
        ),
        migrations.CreateModel(
            name='SuivreAffaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSuivre', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date de suivi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification suivi')),
            ],
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDecision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('typeDecision', models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Vide-du-délibéré', 'Vidé du délibéré'), ('Radie', 'Radie'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation')], null=True, verbose_name='Type decision')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('president', models.TextField(blank=True, null=True, verbose_name='President')),
                ('greffier', models.TextField(blank=True, null=True, verbose_name='Greffier')),
                ('dateDecision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('prochaineAudience', models.DateField(blank=True, null=True, verbose_name='Prochaine audience')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles', verbose_name='Affaire_decision')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAffaire', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numOrdre', models.IntegerField(verbose_name="Numéro d'ordre")),
                ('numRg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rg')),
                ('numRp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rp')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('mandatDepot', models.TextField(blank=True, null=True, verbose_name='Mandats de Dépôt')),
                ('detention', models.TextField(blank=True, null=True, verbose_name='Detention')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Prevention')),
                ('natureInfraction', models.TextField(blank=True, null=True, verbose_name='Nature des infractions')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('prevenus', models.TextField(blank=True, null=True, verbose_name='Prévenus')),
                ('demandeurs', models.TextField(blank=True, null=True, verbose_name='Demandeurs')),
                ('defendeurs', models.TextField(blank=True, null=True, verbose_name='Défendeurs')),
                ('appelants', models.TextField(blank=True, null=True, verbose_name='Appelants')),
                ('intimes', models.TextField(blank=True, null=True, verbose_name='Intimés')),
                ('partieCiviles', models.TextField(blank=True, null=True, verbose_name='Parties civiles')),
                ('civileResponsables', models.TextField(blank=True, null=True, verbose_name='Civiles Responsables')),
                ('dateEnrollement', models.DateField(blank=True, null=True, verbose_name="Date d'enrollement")),
                ('dateAudience', models.DateField(blank=True, null=True, verbose_name="Date d'audience")),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True, verbose_name="Type d'audience")),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRole', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section')),
                ('president', models.TextField(blank=True, null=True, verbose_name='President(e)')),
                ('juge', models.TextField(blank=True, null=True, verbose_name='Juge consulaire')),
                ('assesseur', models.TextField(blank=True, null=True, verbose_name='Assesseur')),
                ('assesseur1', models.TextField(blank=True, null=True, verbose_name='1er Ass')),
                ('assesseur2', models.TextField(blank=True, null=True, verbose_name='2ème Ass')),
                ('conseillers', models.TextField(blank=True, null=True, verbose_name='Conseillers')),
                ('ministerePublic', models.TextField(blank=True, null=True, verbose_name='Ministère public')),
                ('greffier', models.TextField(blank=True, null=True, verbose_name='Greffier(e)')),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True, verbose_name="Type d'audience")),
                ('dateEnreg', models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement")),
                ('filePath', models.TextField(blank=True, null=True, verbose_name='Piece jointe')),
                ('procureurMilitaire', models.TextField(blank=True, null=True, verbose_name='Procureur Militaire')),
                ('subtituts', models.TextField(blank=True, null=True, verbose_name='Subtitut')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
        migrations.AddField(
            model_name='affaireroles',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.roles', verbose_name='Role'),
        ),
    ]
