# Generated by Django 5.2.5 on 2025-09-20 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffaireRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAffaire', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numOrdre', models.IntegerField(verbose_name="Numéro d'ordre")),
                ('numRg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rg')),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('mandatDepot', models.TextField(blank=True, null=True, verbose_name='Mandats de Dépôt')),
                ('detention', models.TextField(blank=True, null=True, verbose_name='Detention')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Prevention')),
                ('natureInfraction', models.TextField(blank=True, null=True, verbose_name='Nature des infractions')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('prevenus', models.TextField(blank=True, null=True, verbose_name='Prévenus')),
                ('demandeurs', models.TextField(blank=True, null=True, verbose_name='Demandeurs')),
                ('defendeurs', models.TextField(blank=True, null=True, verbose_name='Défendeurs')),
                ('appelants', models.TextField(blank=True, null=True, verbose_name='Appelants')),
                ('intimes', models.TextField(blank=True, null=True, verbose_name='Intimés')),
                ('partieCiviles', models.TextField(blank=True, null=True, verbose_name='Parties civiles')),
                ('civileResponsables', models.TextField(blank=True, null=True, verbose_name='Civiles Responsables')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire')),
                ('decision', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('typeDecision', models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('president', models.TextField(blank=True, null=True)),
                ('greffier', models.TextField(blank=True, null=True)),
                ('dateDecision', models.DateField(blank=True, null=True)),
                ('dispositif', models.TextField(blank=True, null=True)),
                ('prochaineAudience', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDecision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section')),
                ('typeDecision', models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True, verbose_name='Type decision')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('president', models.TextField(blank=True, null=True, verbose_name='President')),
                ('greffier', models.TextField(blank=True, null=True, verbose_name='Greffier')),
                ('dateDecision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('dispositif', models.TextField(blank=True, null=True, verbose_name='Dispositif')),
                ('prochaineAudience', models.DateField(blank=True, null=True, verbose_name='Prochaine audience')),
                ('statut', models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAffaire', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numOrdre', models.IntegerField(verbose_name="Numéro d'ordre")),
                ('numRg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rg')),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('demandeurs', models.TextField(blank=True, null=True, verbose_name='Demandeurs')),
                ('defendeurs', models.TextField(blank=True, null=True, verbose_name='Défendeurs')),
                ('dateEnrollement', models.DateField(blank=True, null=True, verbose_name="Date d'enrollement")),
                ('dateAudience', models.DateField(blank=True, null=True, verbose_name="Date d'audience")),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True, verbose_name="Type d'audience")),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
                ('statut', models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True, verbose_name='Statut')),
                ('motifAnnulation', models.TextField(blank=True, null=True, verbose_name='Motif annulation')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOrdre', models.IntegerField()),
                ('numRg', models.CharField(blank=True, max_length=200, null=True)),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('demandeurs', models.TextField(blank=True, null=True)),
                ('defendeurs', models.TextField(blank=True, null=True)),
                ('dateEnrollement', models.DateField(blank=True, null=True)),
                ('dateAudience', models.DateField(blank=True, null=True)),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('statut', models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True)),
                ('motifAnnulation', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDefilant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('actif', models.BooleanField(default=True, verbose_name='Afficher ce message')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRole', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section')),
                ('president', models.TextField(blank=True, null=True, verbose_name='President(e)')),
                ('juge', models.TextField(blank=True, null=True, verbose_name='Juge consulaire')),
                ('assesseur', models.TextField(blank=True, null=True, verbose_name='Assesseur')),
                ('assesseur1', models.TextField(blank=True, null=True, verbose_name='1er Ass')),
                ('assesseur2', models.TextField(blank=True, null=True, verbose_name='2ème Ass')),
                ('conseillers', models.TextField(blank=True, null=True, verbose_name='Conseillers')),
                ('ministerePublic', models.TextField(blank=True, null=True, verbose_name='Ministère public')),
                ('greffier', models.TextField(blank=True, null=True, verbose_name='Greffier(e)')),
                ('typeAudience', models.TextField(blank=True, choices=[('Refere', 'Référé'), ('Fond', 'Fond')], null=True, verbose_name="Type d'audience")),
                ('dateEnreg', models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement")),
                ('filePath', models.TextField(blank=True, null=True, verbose_name='Piece jointe')),
                ('procureurMilitaire', models.TextField(blank=True, null=True, verbose_name='Procureur Militaire')),
                ('subtituts', models.TextField(blank=True, null=True, verbose_name='Subtitut')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation')),
                ('statut', models.TextField(blank=True, choices=[('En-attente', 'En attente'), ('Valider', 'Validé')], default='En-attente', null=True, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='SuivreAffaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSuivre', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date de suivi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification suivi')),
            ],
        ),
    ]
