# Generated by Django 5.2.5 on 2025-09-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('start', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affaireroles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles'),
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions'),
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisions',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles', verbose_name='Affaire_decision'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction'),
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='role.decisions'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction'),
        ),
        migrations.AddField(
            model_name='enrollementhistory',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='start.juridictions'),
        ),
        migrations.AddField(
            model_name='enrollementhistory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollementhistory',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='role.enrollement'),
        ),
        migrations.AddField(
            model_name='roles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='roles',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction'),
        ),
        migrations.AddField(
            model_name='affaireroles',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.roles', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='suivreaffaire',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Suiveur'),
        ),
        migrations.AddField(
            model_name='suivreaffaire',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles'),
        ),
        migrations.AddField(
            model_name='suivreaffaire',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction'),
        ),
    ]
