# Generated by Django 5.2.5 on 2025-09-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greffe', '0002_account_first_name_account_last_name_and_more'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaireroles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greffe.account', verbose_name='Creer par'),
        ),
        migrations.AlterField(
            model_name='decisionhistory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='greffe.account'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greffe.account', verbose_name='Creer par'),
        ),
        migrations.AlterField(
            model_name='enrollement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greffe.account', verbose_name='Creer par'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greffe.account', verbose_name='Creer par'),
        ),
    ]
