# Generated by Django 5.0.3 on 2025-08-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_initial'),
        ('start', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDefilant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('actif', models.BooleanField(default=True, verbose_name='Afficher ce message')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='numRp',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='appelants',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='civileResponsables',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='detention',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='intimes',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='mandatDepot',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='natureInfraction',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='numRp',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='partieCiviles',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='prevenus',
        ),
        migrations.AddField(
            model_name='affaireroles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='affaireroles',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='dispositif',
            field=models.TextField(blank=True, null=True, verbose_name='Dispositif'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='section',
            field=models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='statut',
            field=models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='motifAnnulation',
            field=models.TextField(blank=True, null=True, verbose_name='Motif annulation'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='statut',
            field=models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='roles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='roles',
            name='statut',
            field=models.TextField(blank=True, choices=[('En-attente', 'En attente'), ('Valider', 'Validé')], default='En-attente', null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True, verbose_name='Type decision'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='typeAudience',
            field=models.TextField(blank=True, choices=[('Refere', 'Référé'), ('Fond', 'Fond')], null=True, verbose_name="Type d'audience"),
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('typeDecision', models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('president', models.TextField(blank=True, null=True)),
                ('greffier', models.TextField(blank=True, null=True)),
                ('dateDecision', models.DateField(blank=True, null=True)),
                ('dispositif', models.TextField(blank=True, null=True)),
                ('prochaineAudience', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='role.decisions')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOrdre', models.IntegerField()),
                ('numRg', models.CharField(blank=True, max_length=200, null=True)),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('demandeurs', models.TextField(blank=True, null=True)),
                ('defendeurs', models.TextField(blank=True, null=True)),
                ('dateEnrollement', models.DateField(blank=True, null=True)),
                ('dateAudience', models.DateField(blank=True, null=True)),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('statut', models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True)),
                ('motifAnnulation', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='start.juridictions')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='role.enrollement')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
