# Generated by Django 5.0.3 on 2025-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_messagedefilant_remove_affaireroles_numrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionhistory',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
    ]
