# Generated by Django 5.2.5 on 2025-09-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomNom', models.TextField(verbose_name='Prenom et Nom')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
        migrations.CreateModel(
            name='Conseillers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomNom', models.TextField(verbose_name='Prenom et Nom')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
        migrations.CreateModel(
            name='Presidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomNom', models.TextField(verbose_name='Prenom et Nom')),
                ('chambre', models.TextField(blank=True, null=True, verbose_name='Chambre')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.juridictions', verbose_name='Juridiction')),
            ],
        ),
    ]
