# Generated by Django 5.0.3 on 2025-07-05 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteAnterieure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite_precedente', models.BooleanField(default=False, verbose_name="Exercice d'une précédente activité")),
                ('type_activite', models.CharField(blank=True, choices=[('commercial', 'Commerciale'), ('other', 'Autre')], max_length=20, null=True, verbose_name="Nature de l'activité")),
                ('details_autre_activite', models.CharField(blank=True, max_length=255, null=True, verbose_name="Détails sur l'autre activité")),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin (mois et année)')),
                ('rccm_precedent', models.CharField(blank=True, max_length=100, null=True, verbose_name="Précédent RCCM (s'il y a lieu)")),
                ('etablissement_principal', models.TextField(blank=True, null=True, verbose_name='Établissement principal')),
                ('etablissements_secondaires', models.TextField(blank=True, null=True, verbose_name='Établissements secondaires')),
                ('rccm_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name="RCCM principal (s'il y a lieu)")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse géographique et postale')),
            ],
            options={
                'verbose_name': 'Activité antérieure',
                'verbose_name_plural': 'Activités antérieures',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('rccm', models.TextField(blank=True, null=True, verbose_name='N')),
                ('activites', models.TextField(blank=True, null=True, verbose_name='Activités')),
                ('activitesAjouter', models.TextField(blank=True, null=True, verbose_name='Activités Ajoutées')),
                ('activitesSupprimer', models.TextField(blank=True, null=True, verbose_name='Activités Supprimées')),
                ('activitesActualiser', models.TextField(blank=True, null=True, verbose_name='Activités Actualisées')),
                ('adresseEtablissement', models.TextField(blank=True, null=True, verbose_name='Adresse etablissement')),
                ('ancienneAdresse', models.TextField(blank=True, null=True, verbose_name='Ancienne adresse')),
                ('nouvelleAdresse', models.TextField(blank=True, null=True, verbose_name='Nouvelle adresse')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementSecondaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('rccm', models.TextField(blank=True, null=True, verbose_name='N')),
                ('activites', models.TextField(blank=True, null=True, verbose_name='Activités')),
                ('activitesAjouter', models.TextField(blank=True, null=True, verbose_name='Activités Ajoutées')),
                ('activitesSupprimer', models.TextField(blank=True, null=True, verbose_name='Activités Supprimées')),
                ('activitesActualiser', models.TextField(blank=True, null=True, verbose_name='Activités Actualisées')),
                ('autresActivites', models.TextField(blank=True, null=True, verbose_name='Autres Activités')),
                ('adresseEtablissement', models.TextField(blank=True, null=True, verbose_name='Adresse etablissement')),
                ('ancienneAdresse', models.TextField(blank=True, null=True, verbose_name='Ancienne adresse')),
                ('nouvelleAdresse', models.TextField(blank=True, null=True, verbose_name='Nouvelle adresse')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation etablissement secondaire')),
            ],
        ),
        migrations.CreateModel(
            name='Formalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRccm', models.TextField(blank=True, choices=[('PERSONNE PHYSIQUE', 'Personne physique'), ('PERSONNE MORALE', 'Personne morale')], null=True, verbose_name='Type Rccm')),
                ('numeroFormalite', models.TextField(blank=True, null=True, verbose_name='Numéro Formalite')),
                ('denomination', models.TextField(blank=True, null=True, verbose_name='Denomination')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('mandataire', models.TextField(blank=True, null=True, verbose_name='Mandataire')),
                ('siegeSocial', models.TextField(blank=True, null=True, verbose_name='Siege Social')),
                ('typeFormalite', models.TextField(blank=True, choices=[('Modification', 'Modification'), ('Radiation', 'Radiation'), ('Dissolution', 'Dissolution')], null=True, verbose_name='Type Formalité')),
                ('optionActivite', models.TextField(blank=True, choices=[('Rajout', 'Rajout'), ('Suppression', 'Suppression'), ('Suppression_et_Rajout', 'Suppression et Rajout'), ('Changement', 'Changement')], null=True, verbose_name='Option activite')),
                ('declarationModificative', models.TextField(blank=True, choices=[("A L'ACTIVITE", "L'activite"), ('A LA DENOMINATION', 'La dénomination'), ('AU SIEGE SOCIAL', 'Au siège Social')], null=True, verbose_name='Déclaration modificative')),
                ('dateModification', models.DateField(blank=True, null=True, verbose_name='Date Modification')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation formalité')),
                ('formaliteSignee', models.FileField(blank=True, null=True, upload_to='formalite_signees/', verbose_name='Formalité signée')),
            ],
        ),
        migrations.CreateModel(
            name='Foyer_personne_physique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjoint', models.TextField(blank=True, null=True, verbose_name='Conjoint')),
                ('nomComplet', models.TextField(blank=True, null=True, verbose_name='Nom et prenom')),
                ('dateLieuMariage', models.TextField(blank=True, null=True, verbose_name='Date et lieu de mariage')),
                ('optionMatrimoniale', models.TextField(blank=True, null=True, verbose_name='Option matrimoniale')),
                ('regimeMatrimoniale', models.TextField(blank=True, null=True, verbose_name='Regime matrimoniale')),
                ('demandeSeparationBien', models.TextField(blank=True, null=True, verbose_name='Demande en séparation de biens')),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreCivil', models.TextField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], null=True, verbose_name='Titre civil')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('typeDemande', models.TextField(blank=True, choices=[('Une_demande_de_modification_de_la_personne_physique_et_ou_de_son_etablissement_principale', 'Une demande de modification de la personne physique et ou de son etablissement principale'), ('Une demande_de_modification_dun_etablissement_secondaire_ou_une_succursale', "Une demande de modification d'un etablissement secondaire ou une succursale")], null=True, verbose_name='Demande')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation gerant')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreCivil', models.TextField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], null=True, verbose_name='Titre civil')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naisssance')),
                ('nationnalite', models.TextField(blank=True, null=True, verbose_name='Nationnalité')),
                ('adressePostale', models.TextField(blank=True, null=True, verbose_name='Adresse postale')),
                ('telephone', models.TextField(blank=True, null=True, verbose_name='Telephone')),
                ('domicile', models.TextField(blank=True, null=True, verbose_name='Domicile personnel')),
                ('ville', models.TextField(blank=True, null=True, verbose_name='Ville')),
                ('quartier', models.TextField(blank=True, null=True, verbose_name='Quartier')),
                ('autrePrecision', models.TextField(blank=True, null=True, verbose_name='Autres precisions')),
                ('coordonneesElectro', models.TextField(blank=True, null=True, verbose_name='Coordonnées electroniques')),
                ('situationMatrimoniale', models.TextField(blank=True, choices=[('Celibataire', 'Célibataire'), ('Marie(e)', 'Marié(e)'), ('Veuf(e)', 'Veuf(e)'), ('Divorce(e)', 'Divorcé(e)')], null=True, verbose_name='Situation matrimonial')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation personne physique')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnePhysiqueEngager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naisssance')),
                ('nationnalite', models.TextField(blank=True, null=True, verbose_name='Nationnalité')),
                ('domicile', models.TextField(blank=True, null=True, verbose_name='Domicile personnel')),
                ('modeDomicilier', models.TextField(blank=True, choices=[('Partante', 'Partante'), ('Nouvelle', 'Nouvelle'), ('En_place', 'En place')], null=True, verbose_name='Mode domicilier')),
                ('objetModification', models.TextField(blank=True, null=True, verbose_name='Objet Modification')),
                ('dateModification2', models.DateField(blank=True, null=True, verbose_name='Date modification')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation personne engager')),
            ],
        ),
        migrations.CreateModel(
            name='Rccm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRccm', models.TextField(blank=True, null=True, verbose_name='Numéro Rccm')),
                ('dateEnreg', models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement")),
                ('forme_juridique', models.CharField(blank=True, default='SARL', max_length=50, null=True, verbose_name='Forme Juridique')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social')),
                ('nom_banque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la Banque')),
                ('numero_compte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de Compte')),
                ('duree', models.IntegerField(blank=True, null=True, verbose_name='Durée (en années)')),
                ('rccm_file', models.FileField(blank=True, null=True, upload_to='rccm_files/', verbose_name='Fichier associé')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation Rccm')),
            ],
        ),
    ]
