# Generated by Django 5.0.3 on 2025-07-05 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rccm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Formalité Creer par'),
        ),
        migrations.AddField(
            model_name='etablissementsecondaire',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='foyer_personne_physique',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='gerant',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='personnephysique',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='foyer_personne_physique',
            name='personnePhysique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.personnephysique', verbose_name='personne physique'),
        ),
        migrations.AddField(
            model_name='personnephysiqueengager',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
        migrations.AddField(
            model_name='rccm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rccm Creer par'),
        ),
        migrations.AddField(
            model_name='formalite',
            name='rccm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.rccm', verbose_name='Rccm'),
        ),
    ]
