# Generated by Django 5.2.5 on 2025-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.TextField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Me', 'Maître')], default='M.')),
                ('nom', models.TextField()),
                ('prenom', models.TextField(blank=True)),
                ('fonction', models.TextField(choices=[('avocat', 'Avocat(e)'), ('notaire', 'Notaire'), ('huissier', 'Huissier de justice'), ('expert', 'Expert judiciaire'), ('autre', 'Autre')], default='avocat')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact professionnel',
                'verbose_name_plural': 'Contacts professionnels',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
