# Generated by Django 5.0.3 on 2024-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='objet_cible',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
