# Generated by Django 5.1.1 on 2025-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification_objet_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='objet_cible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
