"""
Django settings for judicalex-gn project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d2c38^i8%#(sfpkd(f85e!a0b2wp*ec466l_^ux8(i#q1m@hin'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # ✅ UNIQUEMENT TOKEN
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ]
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django apps
    'django.contrib.sites',

    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'start',
    'role',
    'greffe',
    'magistrats',
    'users.apps.UsersConfig',
    'blog',
    'rccm',
    'divers',
    'backoffice',
    'rest_framework',
    'rest_framework.authtoken',
    
]

AUTH_USER_MODEL = 'users.Account'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     # Allauth middleware requis
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'judicalex-gn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Assure-toi que 'templates/' est inclus ici
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backoffice.context_processors.notifications_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'judicalex-gn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'judicalex_gn',
        'USER': 'famoussa',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SITE_ID = 2


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# En local, on peut avoir des fichiers dans BASE_DIR/static
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]



# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'vps106526.serveur-vps.net'       # Remplacez par le serveur SMTP de votre fournisseur (ex: smtp.gmail.com)
EMAIL_PORT = 465                       # Port SMTP (utilisez 465 pour SSL, ou 587 pour TLS)
EMAIL_USE_TLS = False                   # Utilisez TLS si le port est 587, sinon mettez EMAIL_USE_SSL à True
EMAIL_USE_SSL = True                  # Utilisez SSL si le port est 465
EMAIL_HOST_USER = 'contact@judicalex-gn.org' # Votre adresse email
EMAIL_HOST_PASSWORD = 'Jud@2025!'      # Mot de passe de l'email
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER       # Adresse utilisée pour l’envoi des emails


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '187515087001-ti3f89lqaacl0hsagicideq5bjkfve7s.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Active la confirmation d’email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # email obligatoire et doit être vérifié
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Judicialex] "
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # pas de vérif email via social login
# Pour forcer l'envoi en multipart (texte + html)
ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = "users/email/email_confirmation_message.html"

# Par défaut, allauth gère déjà les emails
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_USERNAME_REQUIRED = True


ACCOUNT_ADAPTER = "users.adapter.CustomAccountAdapter"


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# En production, collectstatic les envoie ici
STATIC_ROOT = BASE_DIR / "staticfiles"

